services:
  app:
    build: .
    container_name: newsblog
    volumes:
      - ./newsblog:/app/newsblog
    ports:
      - 8000:8000
    command: >
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        gunicorn Blog.wsgi:application --bind 0.0.0.0:8000
      "

